<?php

namespace Database\Seeders;

use App\Models\Collection;
use App\Models\Variety;
use Illuminate\Database\Seeder;

class VarietySeeder extends Seeder
{
    /**
     * Seed authentic material varieties for the 8 canonical ELIOR collections.
     * Content is strictly descriptive and defensible without speculative lab specs.
     */
    public function run(): void
    {
        $varietiesByCollection = [
            'italian-marble' => [
                [
                    'name' => 'Statuario Extra',
                    'slug' => 'statuario-extra',
                    'color_family' => 'White',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A legendary white marble distinguished by its luminous background and dramatic, bold grey veining moving across the surface with monumental grace.',
                    'features' => ['Luminous crystalline ground', 'Dramatic broad veining', 'Exceptional bookmatch capability'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Calacatta Gold',
                    'slug' => 'calacatta-gold',
                    'color_family' => 'Warm White',
                    'finishes' => ['Polished', 'Honed', 'Satin'],
                    'description' => 'Coveted for its warm ivory ground accented by golden honey ribbons and soft taupe veining, bringing warmth and prestige to architectural interiors.',
                    'features' => ['Warm golden ribbons', 'Refined ivory base', 'Balanced tonal warmth'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Carrara Bianco',
                    'slug' => 'carrara-bianco',
                    'color_family' => 'Soft Grey-White',
                    'finishes' => ['Polished', 'Honed', 'Brushed'],
                    'description' => 'The classical foundation of architectural stone, featuring a soft white-to-light-grey ground with gentle feathered graphite veining.',
                    'features' => ['Subtle feathered veining', 'Timeless architectural appeal', 'Even mineral distribution'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Arabescato Vagli',
                    'slug' => 'arabescato-vagli',
                    'color_family' => 'White & Charcoal',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'Distinguished by its distinctive brecciated circular veining where dark charcoal and dusty grey rings frame pure white islands.',
                    'features' => ['Brecciated oval veining', 'High visual contrast', 'Striking monolithic character'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'granites' => [
                [
                    'name' => 'Black Galaxy',
                    'slug' => 'black-galaxy',
                    'color_family' => 'Deep Black',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A deep obsidian granite illuminated by naturally occurring golden and copper bronzite specks that catch ambient light like distant stars.',
                    'features' => ['Golden bronzite flakes', 'Deep midnight ground', 'Exceptional wear resistance'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Steel Grey',
                    'slug' => 'steel-grey',
                    'color_family' => 'Charcoal Grey',
                    'finishes' => ['Honed', 'Leathered', 'Lappato'],
                    'description' => 'A sophisticated medium-to-dark grey stone with subtle tonal variations and fine crystalline flecks, offering calm neutrality for minimalist spaces.',
                    'features' => ['Understated mineral grain', 'Neutral architectural tone', 'Tactile textured options'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tan Brown',
                    'slug' => 'tan-brown',
                    'color_family' => 'Earthy Brown',
                    'finishes' => ['Polished', 'Flamed', 'Honed'],
                    'description' => 'A warm, richly patterned igneous stone characterized by chocolate, burnt amber and dark grey feldspar crystals embedded in a black matrix.',
                    'features' => ['Rich feldspar patterns', 'Warm earth palette', 'Durable monolithic presence'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Viscon White',
                    'slug' => 'viscon-white',
                    'color_family' => 'White & Grey',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A dynamic flowing granite composed of sweeping swirls in shades of white, silver, and smoky charcoal that evoke organic topography.',
                    'features' => ['Sweeping mineral waves', 'Dynamic visual flow', 'Versatile indoor/outdoor tone'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'slate-stone' => [
                [
                    'name' => 'Charcoal Cleft Slate',
                    'slug' => 'charcoal-cleft-slate',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'Naturally split metamorphic slate revealing tactile cleavage planes and deep charcoal tones that create rich shadow play when raked by directional light.',
                    'features' => ['Authentic riven texture', 'Non-reflective deep tone', 'Rich tactile relief'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kund Multi Slate',
                    'slug' => 'kund-multi-slate',
                    'color_family' => 'Multi Earth',
                    'finishes' => ['Natural Cleft', 'Tumbled'],
                    'description' => 'An organic palette of rust, plum, sage, and ochre ribbons woven across a split slate surface, celebrating pure geological variation.',
                    'features' => ['Natural earthy tonal range', 'Distinctive cleavage planes', 'Landscape and terrace harmony'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Copper Quartzite Slate',
                    'slug' => 'copper-quartzite-slate',
                    'color_family' => 'Copper & Bronze',
                    'finishes' => ['Natural Cleft', 'Brushed'],
                    'description' => 'Metamorphic slate infused with micaceous mineral layers that impart subtle metallic copper sheen across warm grey stone.',
                    'features' => ['Micaceous metallic sheen', 'Warm bronze reflections', 'High dimensional stability'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Silver Grey Slate',
                    'slug' => 'silver-grey-slate',
                    'color_family' => 'Muted Silver',
                    'finishes' => ['Honed', 'Natural Cleft'],
                    'description' => 'A cool, quiet silver-grey slate with fine foliation and subtle tonal gradients, ideally suited for understated contemporary wall cladding.',
                    'features' => ['Subtle linear foliation', 'Serene architectural grey', 'Refined interior presence'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'limestones' => [
                [
                    'name' => 'Kota Blue Limestone',
                    'slug' => 'kota-blue-limestone',
                    'color_family' => 'Steel Blue-Grey',
                    'finishes' => ['Natural', 'Honed', 'Polished', 'Antique'],
                    'description' => 'A dense, fine-grained dolomitic limestone exhibiting tranquil greenish-blue tones, celebrated for interior flooring and exterior courtyards.',
                    'features' => ['Cool tranquil blue-grey', 'Fine compact grain', 'Exceptional thermal comfort'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Yellow Limestone',
                    'slug' => 'tandur-yellow-limestone',
                    'color_family' => 'Warm Honey-Gold',
                    'finishes' => ['Natural', 'Honed', 'Brushed'],
                    'description' => 'Radiant golden-yellow sedimentary stone with subtle ochre patterning and soft texture, capturing sunlight and warming large architectural spaces.',
                    'features' => ['Warm golden ambiance', 'Soft natural texture', 'Historic paving heritage'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Crema Bello',
                    'slug' => 'crema-bello',
                    'color_family' => 'Cream & Sand',
                    'finishes' => ['Honed', 'Velvet', 'Brushed'],
                    'description' => 'A tranquil warm cream limestone with tiny micro-fossil deposits, creating a soothing monochromatic surface for light-drenched villas.',
                    'features' => ['Warm neutral cream palette', 'Gentle micro-fossil texture', 'Seamless large-format elegance'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Jura Beige',
                    'slug' => 'jura-beige',
                    'color_family' => 'Beige & Grey',
                    'finishes' => ['Honed', 'Sandblasted'],
                    'description' => 'An iconic architectural limestone rich with prehistoric ammonite and marine fossils set in a calm beige-grey matrix.',
                    'features' => ['Prehistoric fossil imprints', 'Balanced warm-grey neutral', 'High architectural pedigree'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'sandstone' => [
                [
                    'name' => 'Dholpur Beige Sandstone',
                    'slug' => 'dholpur-beige-sandstone',
                    'color_family' => 'Warm Beige / Buff',
                    'finishes' => ['Natural Cleft', 'Honed', 'Shot Blasted'],
                    'description' => 'The celebrated benchmark of Indian architectural sandstone, quarried in Rajasthan. Distinguished by its uniform warm buff-beige tonality, subtle sedimentary layers, and remarkable thermal insulation.',
                    'features' => ['Uniform warm beige hue', 'Naturally slip resistant', 'High thermal resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Rainbow Sandstone',
                    'slug' => 'rainbow-sandstone',
                    'color_family' => 'Multi-tone Earth & Ochre',
                    'finishes' => ['Honed', 'Sawn', 'Brushed'],
                    'description' => 'A visually captivating fine-grained quartz sandstone with dramatic concentric waves and fluid color striations ranging from violet-brown and ochre to golden sand.',
                    'features' => ['Fluid sedimentary wave patterns', 'Rich warm earth striations', 'Distinct statement surface'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Teakwood Sandstone',
                    'slug' => 'teakwood-sandstone',
                    'color_family' => 'Golden Tan / Wood Grain',
                    'finishes' => ['Honed', 'Sawn', 'Sandblasted'],
                    'description' => 'Remarkably reminiscent of natural timber grain, this dense sedimentary stone displays warm golden-tan backgrounds traversed by linear brownish-yellow timber-like swirl patterns.',
                    'features' => ['Distinct wood-grain veining', 'Warm acoustic & tactile feel', 'Ideal for exterior feature walls'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Mandana Stone',
                    'slug' => 'mandana-stone',
                    'color_family' => 'Chocolate Red / Plum',
                    'finishes' => ['Natural Cleft', 'Honed', 'Calibrated'],
                    'description' => 'A dense, acid-resistant quartzitic sandstone with rich chocolate-red and plum undertones, known for centuries as one of the hardest and most resilient natural paving stones.',
                    'features' => ['Acid & frost resistant', 'Deep rich terracotta-plum tone', 'Heavy-duty architectural paving'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'cobble-stones' => [
                [
                    'name' => 'Grey Granite Cobbles',
                    'slug' => 'grey-granite-cobbles',
                    'color_family' => 'Silver & Charcoal',
                    'finishes' => ['Hand-Split', 'Flamed', 'Tumbled'],
                    'description' => 'Hand-split granite cobblestone blocks with textured tops and natural sides, creating timeless textured driveways and garden paths.',
                    'features' => ['Hand-split natural texture', 'Robust load-bearing form', 'Classical cobblestone proportions'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Basalt Cobbles',
                    'slug' => 'black-basalt-cobbles',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Split Face', 'Antique Tumbled'],
                    'description' => 'Dense volcanic basalt cubes offering deep matte charcoal tones that turn dramatic jet black when wet with morning dew or rain.',
                    'features' => ['Volcanic mineral density', 'Striking dark ground', 'Rich contrast with landscaping'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Porphyry Cobbles',
                    'slug' => 'porphyry-cobbles',
                    'color_family' => 'Earth Red & Grey',
                    'finishes' => ['Natural Split'],
                    'description' => 'Traditional Italian-style porphyry cobbles displaying a variegated mosaic of warm reddish-brown, violet, and steel grey.',
                    'features' => ['Variegated earth tones', 'Irregular artisan cleft', 'Exceptional outdoor durability'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Sandstone Cobbles',
                    'slug' => 'sandstone-cobbles',
                    'color_family' => 'Warm Buff',
                    'finishes' => ['Hand-Cut', 'Tumbled'],
                    'description' => 'Hand-cut warm buff and ochre stone pavers with gently rounded tumbled edges, delivering antique pedestrian charm.',
                    'features' => ['Gentle tumbled edges', 'Warm Mediterranean buff tone', 'Comfortable barefoot texture'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'pebbles' => [
                [
                    'name' => 'Snow White River Pebbles',
                    'slug' => 'snow-white-river-pebbles',
                    'color_family' => 'Pure White',
                    'finishes' => ['Natural Tumbled', 'Polished'],
                    'description' => 'Pure crystalline white quartz pebbles tumbled by water into smooth rounded forms that bring bright stillness to zen gardens and water features.',
                    'features' => ['Luminous white mineral tone', 'Water-smoothed contours', 'Clean geometric contrast'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Polished Pebbles',
                    'slug' => 'black-polished-pebbles',
                    'color_family' => 'Obsidian Black',
                    'finishes' => ['Polished', 'Waxed'],
                    'description' => 'Deep black river stones polished to an organic satin sheen, creating refined contrast around reflection pools and minimalist planters.',
                    'features' => ['Deep obsidian sheen', 'Silky tactile surface', 'Reflective water interaction'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Mixed Natural River Pebbles',
                    'slug' => 'mixed-natural-river-pebbles',
                    'color_family' => 'Multi-Tone Earth',
                    'finishes' => ['Natural Fluvial'],
                    'description' => 'A curated assortment of earth-toned pebbles spanning charcoal, amber, cream, and terracotta smoothed by ancient river currents.',
                    'features' => ['Authentic fluvial assortment', 'Warm variegated palette', 'Natural drainage and groundcover'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Onyx Amber Pebbles',
                    'slug' => 'onyx-amber-pebbles',
                    'color_family' => 'Translucent Amber',
                    'finishes' => ['Tumbled', 'Semipolished'],
                    'description' => 'Warm honey and caramel stones with subtle translucence that glow warmly when backlit or submerged in shallow water installations.',
                    'features' => ['Translucent honey tones', 'Subtle optical warmth', 'Sculptural accent quality'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'quartz' => [
                [
                    'name' => 'Calacatta Nuvo Quartz',
                    'slug' => 'calacatta-nuvo-quartz',
                    'color_family' => 'Warm White',
                    'finishes' => ['Polished Slab', 'Suede'],
                    'description' => 'Large engineered quartz slabs featuring an opulent creamy white ground traversed by broad, cascading grey veins for monolithic islands.',
                    'features' => ['Large engineered slab format', 'Broad continuous veining', 'Non-porous architectural resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Statuario Classic Quartz',
                    'slug' => 'statuario-classic-quartz',
                    'color_family' => 'Crisp White',
                    'finishes' => ['Polished Slab', 'Matte'],
                    'description' => 'A masterwork engineered quartz surface offering crisp cool-white slab clarity and flowing graphite veining with total pattern consistency.',
                    'features' => ['Crisp white slab continuity', 'Flowing graphite veining', 'Seamless waterfall edge capability'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Eternal Charcoal Quartz',
                    'slug' => 'eternal-charcoal-quartz',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Suede Slab', 'Polished'],
                    'description' => 'An intense deep charcoal engineered quartz slab traversed by fine, luminous white lightning veins for striking contemporary worktops.',
                    'features' => ['Deep charcoal slab depth', 'Fine luminous contrast veins', 'High scratch and stain resistance'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Pure Blanco Quartz',
                    'slug' => 'pure-blanco-quartz',
                    'color_family' => 'Monochrome White',
                    'finishes' => ['Polished Slab'],
                    'description' => 'A pure, minimalist monochromatic white quartz slab offering uninterrupted architectural surface continuity across expansive surfaces.',
                    'features' => ['Pure monochromatic surface', 'Unbroken visual continuity', 'Architectural minimalist clarity'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'sculptures' => [
                [
                    'name' => 'Monolithic Carved Basin',
                    'slug' => 'monolithic-carved-basin',
                    'color_family' => 'Natural Stone',
                    'finishes' => ['Hand-Chiseled', 'Honed Interior'],
                    'description' => 'Carved from a singular block of natural stone with a rugged artisan exterior and a silky honed interior basin that celebrates raw materiality.',
                    'features' => ['Singular solid stone block', 'Dual textured surface finish', 'Bespoke sculptural focal point'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Architectural Stone Totem',
                    'slug' => 'architectural-stone-totem',
                    'color_family' => 'Weathered Stone',
                    'finishes' => ['Fine Bush-Hammered'],
                    'description' => 'A monumental hand-carved stone column with geometric reliefs that functions as a grounding architectural element for courtyards and entryways.',
                    'features' => ['Monumental vertical presence', 'Artisan geometric relief', 'Timeless outdoor permanence'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Fluted Classical Pedestal',
                    'slug' => 'fluted-classical-pedestal',
                    'color_family' => 'White Marble',
                    'finishes' => ['Honed', 'Antique Patina'],
                    'description' => 'A solid white marble pedestal hand-carved with architectural fluting, designed to anchor private art galleries and stately entry foyers.',
                    'features' => ['Hand-carved vertical fluting', 'Noble white marble grain', 'Architectural gallery presentation'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Contemplative Stone Vessel',
                    'slug' => 'contemplative-stone-vessel',
                    'color_family' => 'Dark Basalt',
                    'finishes' => ['Textured Exterior', 'Smooth Bowl'],
                    'description' => 'A wide, shallow contemplative water vessel carved from natural basalt, inviting reflection and stillness into private courtyards.',
                    'features' => ['Organic low-profile form', 'Natural water interaction', 'Quiet meditative presence'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
        ];

        foreach ($varietiesByCollection as $collectionSlug => $varieties) {
            $collection = Collection::where('slug', $collectionSlug)->first();

            if (! $collection) {
                continue;
            }

            foreach ($varieties as $varietyData) {
                Variety::updateOrCreate(
                    [
                        'collection_id' => $collection->id,
                        'slug' => $varietyData['slug'],
                    ],
                    [
                        'name' => $varietyData['name'],
                        'color_family' => $varietyData['color_family'],
                        'finishes' => $varietyData['finishes'],
                        'description' => $varietyData['description'],
                        'features' => $varietyData['features'],
                        'specifications' => [],
                        'is_featured' => $varietyData['is_featured'],
                        'is_active' => true,
                        'sort_order' => $varietyData['sort_order'],
                    ]
                );
            }
        }
    }
}
