<?php

namespace Database\Seeders;

use App\Models\Collection;
use App\Models\Variety;
use Illuminate\Database\Seeder;

class VarietySeeder extends Seeder
{
    /**
     * Seed authentic material varieties for the 9 canonical ELIOR collections.
     * Content is strictly descriptive and defensible without speculative lab specs.
     */
    public function run(): void
    {
        $varietiesByCollection = [
            'italian-marble' => [
                [
                    'name' => 'Sugar Beige',
                    'slug' => 'sugar-beige',
                    'color_family' => 'Sugar Beige',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A refined warm beige marble distinguished by its crystalline foundation traversed by delicate spiderweb-like hairline calcite veins.',
                    'features' => ['Warm sugar-beige ground', 'Spiderweb hairline calcite veins', 'Subtle micro-texture depth'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Ottoman Beige',
                    'slug' => 'ottoman-beige',
                    'color_family' => 'Beige & Taupe',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A prestigious architectural stone characterized by serene horizontal sedimentary strata and flowing linear mineral bands in warm cream and taupe.',
                    'features' => ['Linear sedimentary strata', 'Flowing horizontal bands', 'Warm architectural tone'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Dyna Beige',
                    'slug' => 'dyna-beige',
                    'color_family' => 'Warm Beige',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A luxurious Italian beige marble defined by a warm creamy foundation with subtle crystalline clouds and delicate fossil matrix.',
                    'features' => ['Warm creamy foundation', 'Soft crystalline clouds', 'Refined tactile warmth'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Crema Nuova',
                    'slug' => 'crema-nuova',
                    'color_family' => 'Warm Cream',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'An organic Italian marble showcasing warm cream and soft greige tones with delicate cloudy fossil mottling and crystalline movement.',
                    'features' => ['Warm cream foundation', 'Cloudy fossil mottling', 'Harmonious organic depth'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Satuario',
                    'slug' => 'satuario',
                    'color_family' => 'Pure White & Charcoal',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'The quintessential Italian white marble distinguished by its luminous crystalline white background and dramatic, bold diagonal charcoal veining.',
                    'features' => ['Luminous crystalline white ground', 'Dramatic diagonal charcoal veining', 'Exceptional bookmatch capability'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Platino Grey',
                    'slug' => 'platino-grey',
                    'color_family' => 'Silver-Platinum Grey',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A refined platinum-toned architectural marble featuring an understated silver-grey ground layered with soft cloudy mineral shifts and delicate graphite veining.',
                    'features' => ['Luminous platinum-grey ground', 'Subtle directional mineral currents', 'Exceptional versatility in contemporary spaces'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Mocha Crema Leather',
                    'slug' => 'mocha-crema-leather',
                    'color_family' => 'Warm Mocha & Crema',
                    'finishes' => ['Leathered', 'Brushed', 'Honed'],
                    'description' => 'Distinguished by its rich mocha undertones and warm crema veins, celebrated particularly in a tactile leathered finish that deepens its organic surface patina.',
                    'features' => ['Tactile leathered surface relief', 'Warm earthy mocha-crema palette', 'Rich geological depth and organic warmth'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Vietnam White',
                    'slug' => 'vietnam-white',
                    'color_family' => 'Pristine Pure White',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'Celebrated as one of the purest and most luminous white crystalline marbles in the world, displaying uniform monolithic brightness with near-zero veining.',
                    'features' => ['High-reflectance crystalline purity', 'Uniform monolithic white surface', 'Monumental clarity for architectural planes'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Botochino',
                    'slug' => 'botochino',
                    'color_family' => 'Warm Ivory & Golden Hazel',
                    'finishes' => ['Polished', 'Honed', 'Brushed'],
                    'description' => 'A classical compact limestone-marble with an elegant warm ivory-beige base, enriched by subtle golden-hazel veins and characteristic organic fossil clouds.',
                    'features' => ['Timeless warm ivory-beige ground', 'Delicate golden-hazel micro-veining', 'Durable compact mineral structure'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
            ],
            'granites' => [
                [
                    'name' => 'Black Galaxy Granite',
                    'slug' => 'black-galaxy-granite',
                    'color_family' => 'Deep Obsidian & Gold',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A deep obsidian architectural granite illuminated by naturally occurring golden and copper bronzite specks that catch ambient daylight like distant constellations.',
                    'features' => ['Golden bronzite flakes', 'Deep midnight ground', 'Exceptional structural density'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Steel Grey',
                    'slug' => 'steel-grey',
                    'color_family' => 'Charcoal & Pewter',
                    'finishes' => ['Honed', 'Leathered', 'Lappato'],
                    'description' => 'A calm, monolithic medium-to-dark grey granite characterized by fine crystalline flecks and subtle mineral shifts, offering neutral architectural elegance.',
                    'features' => ['Understated mineral grain', 'Tactile textured options', 'Refined neutral presence'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tan Brown',
                    'slug' => 'tan-brown',
                    'color_family' => 'Earthy Chocolate & Burnt Ochre',
                    'finishes' => ['Polished', 'Flamed', 'Leathered'],
                    'description' => 'An intensely structured igneous stone marked by warm chocolate, burnt amber, and dark grey feldspar crystals embedded in a dense obsidian matrix.',
                    'features' => ['Rich feldspar crystals', 'Warm tectonic palette', 'High compressive strength'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Absolute Black',
                    'slug' => 'absolute-black',
                    'color_family' => 'Solid Deep Black',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'The definitive benchmark for monolithic stone surfaces, presenting an ultra-dense, pure pitch-black fine-grained plane of absolute visual stillness.',
                    'features' => ['Pure monolithic black ground', 'Zero prominent veining', 'Unrivaled architectural stillness'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Chima Pink Granite',
                    'slug' => 'chima-pink-granite',
                    'color_family' => 'Blush Rose & Silver',
                    'finishes' => ['Polished', 'Flamed', 'Honed'],
                    'description' => 'A classical Indian granite showcasing an organic blend of warm rosy-pink potassium feldspars, silvery quartz, and delicate dark biotite specks.',
                    'features' => ['Warm blush mineral tones', 'Balanced crystalline matrix', 'Exceptional exterior durability'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Colonial White',
                    'slug' => 'colonial-white',
                    'color_family' => 'Cotton White & Burgundy Flecks',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A bright, luminous white-to-pale-grey granite accented with delicate smoky grey patches and subtle garnet-red jewel flecks scattered across its surface.',
                    'features' => ['Bright crystalline white base', 'Subtle garnet mineral specks', 'Airy spatial presence'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Burgundy White',
                    'slug' => 'burgundy-white',
                    'color_family' => 'Ivory White & Burgundy Waves',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A dynamic architectural granite distinguished by sweeping ivory-white planes crossed by rhythmic deep burgundy and maroon mineral currents.',
                    'features' => ['Expressive burgundy ribbons', 'Luminous quartz matrix', 'Striking directional movement'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Apple Green',
                    'slug' => 'apple-green',
                    'color_family' => 'Olive & Sage Green',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A rare and distinctive granite exhibiting soft olive and sage-green tones interspersed with pale quartz crystals and fine dark mineral filaments.',
                    'features' => ['Distinctive sage-green palette', 'Natural biophilic harmony', 'Uniform fine-grained density'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Parda Gold',
                    'slug' => 'parda-gold',
                    'color_family' => 'Warm Gold & Amber',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A prestigious golden granite radiating warmth through a golden-ochre foundation animated by undulating waves of taupe, quartz crystal, and dark amber.',
                    'features' => ['Warm golden-ochre warmth', 'Fluid organic flow', 'Rich tactile presence'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
                [
                    'name' => 'River White',
                    'slug' => 'river-white',
                    'color_family' => 'Silvery White & Blue-Grey',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'Celebrated for its sweeping linear rivers of silver-grey and misty blue currents flowing effortlessly across a bright white crystalline landscape.',
                    'features' => ['Continuous linear mineral flow', 'Deep crimson cranberry accents', 'Calm architectural lightness'],
                    'sort_order' => 10,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Nadol Grey',
                    'slug' => 'nadol-grey',
                    'color_family' => 'Ash & Charcoal Grey',
                    'finishes' => ['Flamed', 'Honed', 'Leathered', 'Polished'],
                    'description' => 'An earthy architectural grey granite prized for its balanced salt-and-pepper grain and supreme resilience in exterior landscaping and monumental facades.',
                    'features' => ['Balanced uniform grain', 'Superior slip resistance in flamed finish', 'High civic resilience'],
                    'sort_order' => 11,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Viscon White',
                    'slug' => 'viscon-white',
                    'color_family' => 'White, Silver & Charcoal',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A dramatic flowing granite composed of sweeping swirls in shades of white, silver, and smoky charcoal that evoke organic mountain topography.',
                    'features' => ['Sweeping topographical waves', 'Dynamic visual movement', 'Versatile indoor/outdoor tone'],
                    'sort_order' => 12,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Silk Brown',
                    'slug' => 'silk-brown',
                    'color_family' => 'Warm Taupe & Bronze',
                    'finishes' => ['Leathered', 'Honed', 'Polished'],
                    'description' => 'An understated contemporary stone characterized by soft mocha and silk-brown tones with gentle horizontal striations and warm bronze undertones.',
                    'features' => ['Warm taupe-bronze hues', 'Subtle horizontal grain', 'Luxurious velvet-smooth touch'],
                    'sort_order' => 13,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Alaska White',
                    'slug' => 'alaska-white',
                    'color_family' => 'Frost White & Onyx Black',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A striking frosty blend of brilliant white feldspar, translucent quartz crystals, and bold dramatic patches of onyx-black and dark silver biotite.',
                    'features' => ['High visual contrast', 'Translucent quartz windows', 'Statement monolithic character'],
                    'sort_order' => 14,
                    'is_featured' => true,
                ],
                [
                    'name' => 'White Granite',
                    'slug' => 'white-granite',
                    'color_family' => 'Soft White & Graphite',
                    'finishes' => ['Polished', 'Flamed', 'Honed'],
                    'description' => 'A timeless architectural natural stone presenting an even, refined white foundation speckled with micro-crystals of grey and obsidian.',
                    'features' => ['Consistent mineral distribution', 'Clean minimalist surface', 'Universal spatial application'],
                    'sort_order' => 15,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Foreign Black',
                    'slug' => 'foreign-black',
                    'color_family' => 'Midnight Black & Silver',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'An exotic deep-black granite distinguished by monumental mineral density, high crystalline polish, and subtle metallic silver crystalline flecks.',
                    'features' => ['Exotic deep-black depth', 'Exceptional specular reflectivity', 'Monumental wear resilience'],
                    'sort_order' => 16,
                    'is_featured' => true,
                ],
            ],
            'slate-stone' => [
                [
                    'name' => 'Charcoal Cleft Slate',
                    'slug' => 'charcoal-cleft-slate',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'Naturally split metamorphic slate revealing tactile cleavage planes and deep charcoal tones that create rich shadow play when raked by directional light.',
                    'features' => ['Authentic riven texture', 'Non-reflective deep tone', 'Rich tactile relief'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kund Multi Slate',
                    'slug' => 'kund-multi-slate',
                    'color_family' => 'Multi Earth',
                    'finishes' => ['Natural Cleft', 'Tumbled'],
                    'description' => 'An organic palette of rust, plum, sage, and ochre ribbons woven across a split slate surface, celebrating pure geological variation.',
                    'features' => ['Natural earthy tonal range', 'Distinctive cleavage planes', 'Landscape and terrace harmony'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Copper Quartzite Slate',
                    'slug' => 'copper-quartzite-slate',
                    'color_family' => 'Copper & Bronze',
                    'finishes' => ['Natural Cleft', 'Brushed'],
                    'description' => 'Metamorphic slate infused with micaceous mineral layers that impart subtle metallic copper sheen across warm grey stone.',
                    'features' => ['Micaceous metallic sheen', 'Warm bronze reflections', 'High dimensional stability'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Silver Grey Slate',
                    'slug' => 'silver-grey-slate',
                    'color_family' => 'Muted Silver',
                    'finishes' => ['Honed', 'Natural Cleft'],
                    'description' => 'A cool, quiet silver-grey slate with fine foliation and subtle tonal gradients, ideally suited for understated contemporary wall cladding.',
                    'features' => ['Subtle linear foliation', 'Serene architectural grey', 'Refined interior presence'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'limestones' => [
                [
                    'name' => 'Kota Blue Limestone',
                    'slug' => 'kota-blue-limestone',
                    'color_family' => 'Steel Blue-Grey',
                    'finishes' => ['Natural', 'Honed', 'Polished', 'Antique'],
                    'description' => 'A dense, fine-grained dolomitic limestone exhibiting tranquil greenish-blue tones, celebrated for interior flooring and exterior courtyards.',
                    'features' => ['Cool tranquil blue-grey', 'Fine compact grain', 'Exceptional thermal comfort'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Yellow Limestone',
                    'slug' => 'tandur-yellow-limestone',
                    'color_family' => 'Warm Honey-Gold',
                    'finishes' => ['Natural', 'Honed', 'Brushed'],
                    'description' => 'Radiant golden-yellow sedimentary stone with subtle ochre patterning and soft texture, capturing sunlight and warming large architectural spaces.',
                    'features' => ['Warm golden ambiance', 'Soft natural texture', 'Historic paving heritage'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Crema Bello',
                    'slug' => 'crema-bello',
                    'color_family' => 'Cream & Sand',
                    'finishes' => ['Honed', 'Velvet', 'Brushed'],
                    'description' => 'A tranquil warm cream limestone with tiny micro-fossil deposits, creating a soothing monochromatic surface for light-drenched villas.',
                    'features' => ['Warm neutral cream palette', 'Gentle micro-fossil texture', 'Seamless large-format elegance'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Jura Beige',
                    'slug' => 'jura-beige',
                    'color_family' => 'Beige & Grey',
                    'finishes' => ['Honed', 'Sandblasted'],
                    'description' => 'An iconic architectural limestone rich with prehistoric ammonite and marine fossils set in a calm beige-grey matrix.',
                    'features' => ['Prehistoric fossil imprints', 'Balanced warm-grey neutral', 'High architectural pedigree'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'sandstone' => [
                [
                    'name' => 'Dholpur Beige Sandstone',
                    'slug' => 'dholpur-beige-sandstone',
                    'color_family' => 'Warm Beige / Buff',
                    'finishes' => ['Natural Cleft', 'Honed', 'Shot Blasted'],
                    'description' => 'The celebrated benchmark of Indian architectural sandstone, quarried in Rajasthan. Distinguished by its uniform warm buff-beige tonality, subtle sedimentary layers, and remarkable thermal insulation.',
                    'features' => ['Uniform warm beige hue', 'Naturally slip resistant', 'High thermal resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Rainbow Sandstone',
                    'slug' => 'rainbow-sandstone',
                    'color_family' => 'Multi-tone Earth & Ochre',
                    'finishes' => ['Honed', 'Sawn', 'Brushed'],
                    'description' => 'A visually captivating fine-grained quartz sandstone with dramatic concentric waves and fluid color striations ranging from violet-brown and ochre to golden sand.',
                    'features' => ['Fluid sedimentary wave patterns', 'Rich warm earth striations', 'Distinct statement surface'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Teakwood Sandstone',
                    'slug' => 'teakwood-sandstone',
                    'color_family' => 'Golden Tan / Wood Grain',
                    'finishes' => ['Honed', 'Sawn', 'Sandblasted'],
                    'description' => 'Remarkably reminiscent of natural timber grain, this dense sedimentary stone displays warm golden-tan backgrounds traversed by linear brownish-yellow timber-like swirl patterns.',
                    'features' => ['Distinct wood-grain veining', 'Warm acoustic & tactile feel', 'Ideal for exterior feature walls'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Mandana Stone',
                    'slug' => 'mandana-stone',
                    'color_family' => 'Chocolate Red / Plum',
                    'finishes' => ['Natural Cleft', 'Honed', 'Calibrated'],
                    'description' => 'A dense, acid-resistant quartzitic sandstone with rich chocolate-red and plum undertones, known for centuries as one of the hardest and most resilient natural paving stones.',
                    'features' => ['Acid & frost resistant', 'Deep rich terracotta-plum tone', 'Heavy-duty architectural paving'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'cobble-stones' => [
                [
                    'name' => 'Grey Granite Cobbles',
                    'slug' => 'grey-granite-cobbles',
                    'color_family' => 'Silver & Charcoal',
                    'finishes' => ['Hand-Split', 'Flamed', 'Tumbled'],
                    'description' => 'Hand-split granite cobblestone blocks with textured tops and natural sides, creating timeless textured driveways and garden paths.',
                    'features' => ['Hand-split natural texture', 'Robust load-bearing form', 'Classical cobblestone proportions'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Basalt Cobbles',
                    'slug' => 'black-basalt-cobbles',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Split Face', 'Antique Tumbled'],
                    'description' => 'Dense volcanic basalt cubes offering deep matte charcoal tones that turn dramatic jet black when wet with morning dew or rain.',
                    'features' => ['Volcanic mineral density', 'Striking dark ground', 'Rich contrast with landscaping'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Porphyry Cobbles',
                    'slug' => 'porphyry-cobbles',
                    'color_family' => 'Earth Red & Grey',
                    'finishes' => ['Natural Split'],
                    'description' => 'Traditional Italian-style porphyry cobbles displaying a variegated mosaic of warm reddish-brown, violet, and steel grey.',
                    'features' => ['Variegated earth tones', 'Irregular artisan cleft', 'Exceptional outdoor durability'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Sandstone Cobbles',
                    'slug' => 'sandstone-cobbles',
                    'color_family' => 'Warm Buff',
                    'finishes' => ['Hand-Cut', 'Tumbled'],
                    'description' => 'Hand-cut warm buff and ochre stone pavers with gently rounded tumbled edges, delivering antique pedestrian charm.',
                    'features' => ['Gentle tumbled edges', 'Warm Mediterranean buff tone', 'Comfortable barefoot texture'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'pebbles' => [
                [
                    'name' => 'Snow White River Pebbles',
                    'slug' => 'snow-white-river-pebbles',
                    'color_family' => 'Pure White',
                    'finishes' => ['Natural Tumbled', 'Polished'],
                    'description' => 'Pure crystalline white quartz pebbles tumbled by water into smooth rounded forms that bring bright stillness to zen gardens and water features.',
                    'features' => ['Luminous white mineral tone', 'Water-smoothed contours', 'Clean geometric contrast'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Polished Pebbles',
                    'slug' => 'black-polished-pebbles',
                    'color_family' => 'Obsidian Black',
                    'finishes' => ['Polished', 'Waxed'],
                    'description' => 'Deep black river stones polished to an organic satin sheen, creating refined contrast around reflection pools and minimalist planters.',
                    'features' => ['Deep obsidian sheen', 'Silky tactile surface', 'Reflective water interaction'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Mixed Natural River Pebbles',
                    'slug' => 'mixed-natural-river-pebbles',
                    'color_family' => 'Multi-Tone Earth',
                    'finishes' => ['Natural Fluvial'],
                    'description' => 'A curated assortment of earth-toned pebbles spanning charcoal, amber, cream, and terracotta smoothed by ancient river currents.',
                    'features' => ['Authentic fluvial assortment', 'Warm variegated palette', 'Natural drainage and groundcover'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Onyx Amber Pebbles',
                    'slug' => 'onyx-amber-pebbles',
                    'color_family' => 'Translucent Amber',
                    'finishes' => ['Tumbled', 'Semipolished'],
                    'description' => 'Warm honey and caramel stones with subtle translucence that glow warmly when backlit or submerged in shallow water installations.',
                    'features' => ['Translucent honey tones', 'Subtle optical warmth', 'Sculptural accent quality'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'quartz' => [
                [
                    'name' => 'Calacatta Nuvo Quartz',
                    'slug' => 'calacatta-nuvo-quartz',
                    'color_family' => 'Warm White',
                    'finishes' => ['Polished Slab', 'Suede'],
                    'description' => 'Large engineered quartz slabs featuring an opulent creamy white ground traversed by broad, cascading grey veins for monolithic islands.',
                    'features' => ['Large engineered slab format', 'Broad continuous veining', 'Non-porous architectural resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Statuario Classic Quartz',
                    'slug' => 'statuario-classic-quartz',
                    'color_family' => 'Crisp White',
                    'finishes' => ['Polished Slab', 'Matte'],
                    'description' => 'A masterwork engineered quartz surface offering crisp cool-white slab clarity and flowing graphite veining with total pattern consistency.',
                    'features' => ['Crisp white slab continuity', 'Flowing graphite veining', 'Seamless waterfall edge capability'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Eternal Charcoal Quartz',
                    'slug' => 'eternal-charcoal-quartz',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Suede Slab', 'Polished'],
                    'description' => 'An intense deep charcoal engineered quartz slab traversed by fine, luminous white lightning veins for striking contemporary worktops.',
                    'features' => ['Deep charcoal slab depth', 'Fine luminous contrast veins', 'High scratch and stain resistance'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Pure Blanco Quartz',
                    'slug' => 'pure-blanco-quartz',
                    'color_family' => 'Monochrome White',
                    'finishes' => ['Polished Slab'],
                    'description' => 'A pure, minimalist monochromatic white quartz slab offering uninterrupted architectural surface continuity across expansive surfaces.',
                    'features' => ['Pure monochromatic surface', 'Unbroken visual continuity', 'Architectural minimalist clarity'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'sculptures' => [
                [
                    'name' => 'Monolithic Carved Basin',
                    'slug' => 'monolithic-carved-basin',
                    'color_family' => 'Natural Stone',
                    'finishes' => ['Hand-Chiseled', 'Honed Interior'],
                    'description' => 'Carved from a singular block of natural stone with a rugged artisan exterior and a silky honed interior basin that celebrates raw materiality.',
                    'features' => ['Singular solid stone block', 'Dual textured surface finish', 'Bespoke sculptural focal point'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Architectural Stone Totem',
                    'slug' => 'architectural-stone-totem',
                    'color_family' => 'Weathered Stone',
                    'finishes' => ['Fine Bush-Hammered'],
                    'description' => 'A monumental hand-carved stone column with geometric reliefs that functions as a grounding architectural element for courtyards and entryways.',
                    'features' => ['Monumental vertical presence', 'Artisan geometric relief', 'Timeless outdoor permanence'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Fluted Classical Pedestal',
                    'slug' => 'fluted-classical-pedestal',
                    'color_family' => 'White Marble',
                    'finishes' => ['Honed', 'Antique Patina'],
                    'description' => 'A solid white marble pedestal hand-carved with architectural fluting, designed to anchor private art galleries and stately entry foyers.',
                    'features' => ['Hand-carved vertical fluting', 'Noble white marble grain', 'Architectural gallery presentation'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Contemplative Stone Vessel',
                    'slug' => 'contemplative-stone-vessel',
                    'color_family' => 'Dark Basalt',
                    'finishes' => ['Textured Exterior', 'Smooth Bowl'],
                    'description' => 'A wide, shallow contemplative water vessel carved from natural basalt, inviting reflection and stillness into private courtyards.',
                    'features' => ['Organic low-profile form', 'Natural water interaction', 'Quiet meditative presence'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
        ];

        foreach ($varietiesByCollection as $collectionSlug => $varieties) {
            $collection = Collection::where('slug', $collectionSlug)->first();

            if (! $collection) {
                continue;
            }

            foreach ($varieties as $varietyData) {
                Variety::updateOrCreate(
                    [
                        'collection_id' => $collection->id,
                        'slug' => $varietyData['slug'],
                    ],
                    [
                        'name' => $varietyData['name'],
                        'color_family' => $varietyData['color_family'],
                        'finishes' => $varietyData['finishes'],
                        'description' => $varietyData['description'],
                        'features' => $varietyData['features'],
                        'specifications' => [],
                        'is_featured' => $varietyData['is_featured'],
                        'is_active' => true,
                        'sort_order' => $varietyData['sort_order'],
                    ]
                );
            }
        }
    }
}
