<?php

namespace Database\Seeders;

use App\Models\Collection;
use App\Models\Variety;
use Illuminate\Database\Seeder;

class VarietySeeder extends Seeder
{
    /**
     * Seed authentic material varieties for the 9 canonical ELIOR collections.
     * Content is strictly descriptive and defensible without speculative lab specs.
     */
    public function run(): void
    {
        $varietiesByCollection = [
            'italian-marble' => [
                [
                    'name' => 'Sugar Beige',
                    'slug' => 'sugar-beige',
                    'color_family' => 'Sugar Beige',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A refined warm beige marble distinguished by its crystalline foundation traversed by delicate spiderweb-like hairline calcite veins.',
                    'features' => ['Warm sugar-beige ground', 'Spiderweb hairline calcite veins', 'Subtle micro-texture depth'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Ottoman Beige',
                    'slug' => 'ottoman-beige',
                    'color_family' => 'Beige & Taupe',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A prestigious architectural stone characterized by serene horizontal sedimentary strata and flowing linear mineral bands in warm cream and taupe.',
                    'features' => ['Linear sedimentary strata', 'Flowing horizontal bands', 'Warm architectural tone'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Dyna Beige',
                    'slug' => 'dyna-beige',
                    'color_family' => 'Warm Beige',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A luxurious Italian beige marble defined by a warm creamy foundation with subtle crystalline clouds and delicate fossil matrix.',
                    'features' => ['Warm creamy foundation', 'Soft crystalline clouds', 'Refined tactile warmth'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Crema Nuova',
                    'slug' => 'crema-nuova',
                    'color_family' => 'Warm Cream',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'An organic Italian marble showcasing warm cream and soft greige tones with delicate cloudy fossil mottling and crystalline movement.',
                    'features' => ['Warm cream foundation', 'Cloudy fossil mottling', 'Harmonious organic depth'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Satuario',
                    'slug' => 'satuario',
                    'color_family' => 'Pure White & Charcoal',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'The quintessential Italian white marble distinguished by its luminous crystalline white background and dramatic, bold diagonal charcoal veining.',
                    'features' => ['Luminous crystalline white ground', 'Dramatic diagonal charcoal veining', 'Exceptional bookmatch capability'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Platino Grey',
                    'slug' => 'platino-grey',
                    'color_family' => 'Silver-Platinum Grey',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A refined platinum-toned architectural marble featuring an understated silver-grey ground layered with soft cloudy mineral shifts and delicate graphite veining.',
                    'features' => ['Luminous platinum-grey ground', 'Subtle directional mineral currents', 'Exceptional versatility in contemporary spaces'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Mocha Crema Leather',
                    'slug' => 'mocha-crema-leather',
                    'color_family' => 'Warm Mocha & Crema',
                    'finishes' => ['Leathered', 'Brushed', 'Honed'],
                    'description' => 'Distinguished by its rich mocha undertones and warm crema veins, celebrated particularly in a tactile leathered finish that deepens its organic surface patina.',
                    'features' => ['Tactile leathered surface relief', 'Warm earthy mocha-crema palette', 'Rich geological depth and organic warmth'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Vietnam White',
                    'slug' => 'vietnam-white',
                    'color_family' => 'Pristine Pure White',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'Celebrated as one of the purest and most luminous white crystalline marbles in the world, displaying uniform monolithic brightness with near-zero veining.',
                    'features' => ['High-reflectance crystalline purity', 'Uniform monolithic white surface', 'Monumental clarity for architectural planes'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Botochino',
                    'slug' => 'botochino',
                    'color_family' => 'Warm Ivory & Golden Hazel',
                    'finishes' => ['Polished', 'Honed', 'Brushed'],
                    'description' => 'A classical compact limestone-marble with an elegant warm ivory-beige base, enriched by subtle golden-hazel veins and characteristic organic fossil clouds.',
                    'features' => ['Timeless warm ivory-beige ground', 'Delicate golden-hazel micro-veining', 'Durable compact mineral structure'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
            ],
            'granites' => [
                [
                    'name' => 'Black Galaxy Granite',
                    'slug' => 'black-galaxy-granite',
                    'color_family' => 'Deep Obsidian & Gold',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A deep obsidian architectural granite illuminated by naturally occurring golden and copper bronzite specks that catch ambient daylight like distant constellations.',
                    'features' => ['Golden bronzite flakes', 'Deep midnight ground', 'Exceptional structural density'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Steel Grey',
                    'slug' => 'steel-grey',
                    'color_family' => 'Charcoal & Pewter',
                    'finishes' => ['Honed', 'Leathered', 'Lappato'],
                    'description' => 'A calm, monolithic medium-to-dark grey granite characterized by fine crystalline flecks and subtle mineral shifts, offering neutral architectural elegance.',
                    'features' => ['Understated mineral grain', 'Tactile textured options', 'Refined neutral presence'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tan Brown',
                    'slug' => 'tan-brown',
                    'color_family' => 'Earthy Chocolate & Burnt Ochre',
                    'finishes' => ['Polished', 'Flamed', 'Leathered'],
                    'description' => 'An intensely structured igneous stone marked by warm chocolate, burnt amber, and dark grey feldspar crystals embedded in a dense obsidian matrix.',
                    'features' => ['Rich feldspar crystals', 'Warm tectonic palette', 'High compressive strength'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Absolute Black',
                    'slug' => 'absolute-black',
                    'color_family' => 'Solid Deep Black',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'The definitive benchmark for monolithic stone surfaces, presenting an ultra-dense, pure pitch-black fine-grained plane of absolute visual stillness.',
                    'features' => ['Pure monolithic black ground', 'Zero prominent veining', 'Unrivaled architectural stillness'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Chima Pink Granite',
                    'slug' => 'chima-pink-granite',
                    'color_family' => 'Blush Rose & Silver',
                    'finishes' => ['Polished', 'Flamed', 'Honed'],
                    'description' => 'A classical Indian granite showcasing an organic blend of warm rosy-pink potassium feldspars, silvery quartz, and delicate dark biotite specks.',
                    'features' => ['Warm blush mineral tones', 'Balanced crystalline matrix', 'Exceptional exterior durability'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Colonial White',
                    'slug' => 'colonial-white',
                    'color_family' => 'Cotton White & Burgundy Flecks',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A bright, luminous white-to-pale-grey granite accented with delicate smoky grey patches and subtle garnet-red jewel flecks scattered across its surface.',
                    'features' => ['Bright crystalline white base', 'Subtle garnet mineral specks', 'Airy spatial presence'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Burgundy White',
                    'slug' => 'burgundy-white',
                    'color_family' => 'Ivory White & Burgundy Waves',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'A dynamic architectural granite distinguished by sweeping ivory-white planes crossed by rhythmic deep burgundy and maroon mineral currents.',
                    'features' => ['Expressive burgundy ribbons', 'Luminous quartz matrix', 'Striking directional movement'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Apple Green',
                    'slug' => 'apple-green',
                    'color_family' => 'Olive & Sage Green',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A rare and distinctive granite exhibiting soft olive and sage-green tones interspersed with pale quartz crystals and fine dark mineral filaments.',
                    'features' => ['Distinctive sage-green palette', 'Natural biophilic harmony', 'Uniform fine-grained density'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Parda Gold',
                    'slug' => 'parda-gold',
                    'color_family' => 'Warm Gold & Amber',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A prestigious golden granite radiating warmth through a golden-ochre foundation animated by undulating waves of taupe, quartz crystal, and dark amber.',
                    'features' => ['Warm golden-ochre warmth', 'Fluid organic flow', 'Rich tactile presence'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
                [
                    'name' => 'River White',
                    'slug' => 'river-white',
                    'color_family' => 'Silvery White & Blue-Grey',
                    'finishes' => ['Polished', 'Honed'],
                    'description' => 'Celebrated for its sweeping linear rivers of silver-grey and misty blue currents flowing effortlessly across a bright white crystalline landscape.',
                    'features' => ['Continuous linear mineral flow', 'Deep crimson cranberry accents', 'Calm architectural lightness'],
                    'sort_order' => 10,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Nadol Grey',
                    'slug' => 'nadol-grey',
                    'color_family' => 'Ash & Charcoal Grey',
                    'finishes' => ['Flamed', 'Honed', 'Leathered', 'Polished'],
                    'description' => 'An earthy architectural grey granite prized for its balanced salt-and-pepper grain and supreme resilience in exterior landscaping and monumental facades.',
                    'features' => ['Balanced uniform grain', 'Superior slip resistance in flamed finish', 'High civic resilience'],
                    'sort_order' => 11,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Viscon White',
                    'slug' => 'viscon-white',
                    'color_family' => 'White, Silver & Charcoal',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A dramatic flowing granite composed of sweeping swirls in shades of white, silver, and smoky charcoal that evoke organic mountain topography.',
                    'features' => ['Sweeping topographical waves', 'Dynamic visual movement', 'Versatile indoor/outdoor tone'],
                    'sort_order' => 12,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Silk Brown',
                    'slug' => 'silk-brown',
                    'color_family' => 'Warm Taupe & Bronze',
                    'finishes' => ['Leathered', 'Honed', 'Polished'],
                    'description' => 'An understated contemporary stone characterized by soft mocha and silk-brown tones with gentle horizontal striations and warm bronze undertones.',
                    'features' => ['Warm taupe-bronze hues', 'Subtle horizontal grain', 'Luxurious velvet-smooth touch'],
                    'sort_order' => 13,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Alaska White',
                    'slug' => 'alaska-white',
                    'color_family' => 'Frost White & Onyx Black',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'A striking frosty blend of brilliant white feldspar, translucent quartz crystals, and bold dramatic patches of onyx-black and dark silver biotite.',
                    'features' => ['High visual contrast', 'Translucent quartz windows', 'Statement monolithic character'],
                    'sort_order' => 14,
                    'is_featured' => true,
                ],
                [
                    'name' => 'White Granite',
                    'slug' => 'white-granite',
                    'color_family' => 'Soft White & Graphite',
                    'finishes' => ['Polished', 'Flamed', 'Honed'],
                    'description' => 'A timeless architectural natural stone presenting an even, refined white foundation speckled with micro-crystals of grey and obsidian.',
                    'features' => ['Consistent mineral distribution', 'Clean minimalist surface', 'Universal spatial application'],
                    'sort_order' => 15,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Foreign Black',
                    'slug' => 'foreign-black',
                    'color_family' => 'Midnight Black & Silver',
                    'finishes' => ['Polished', 'Honed', 'Leathered'],
                    'description' => 'An exotic deep-black granite distinguished by monumental mineral density, high crystalline polish, and subtle metallic silver crystalline flecks.',
                    'features' => ['Exotic deep-black depth', 'Exceptional specular reflectivity', 'Monumental wear resilience'],
                    'sort_order' => 16,
                    'is_featured' => true,
                ],
            ],
            'slate-stone' => [
                [
                    'name' => 'Black Slate',
                    'slug' => 'black-slate',
                    'color_family' => 'Deep Charcoal & Obsidian',
                    'finishes' => ['Natural Cleft', 'Honed', 'Antique / Tumbled'],
                    'description' => 'A classic fine-grained metamorphic black slate featuring authentic riven cleavage planes and deep non-reflective charcoal-black depth.',
                    'features' => ['Natural riven split texture', 'Monolithic dark charcoal ground', 'Slip-resistant architectural surface'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Rustic',
                    'slug' => 'black-rustic',
                    'color_family' => 'Charcoal & Rust Iron',
                    'finishes' => ['Natural Cleft', 'Honed', 'Brushed'],
                    'description' => 'Rich dark charcoal slate traversed by organic iron-oxide rust striations and earthy mineral patinas that celebrate raw geological weathering.',
                    'features' => ['Organic rust-patina oxidation', 'Textured cleft cleavage', 'Earthy tactile contrast'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Indian Autumn',
                    'slug' => 'indian-autumn',
                    'color_family' => 'Warm Buff, Ochre & Rose',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'A celebrated North Indian slate featuring a vibrant tapestry of autumn leaves—warm beige, golden ochre, terracotta, and soft rose tones across layered foliation.',
                    'features' => ['Warm autumnal tonal spectrum', 'Fine natural foliation', 'Distinctive landscape character'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Gold Rustic',
                    'slug' => 'gold-rustic',
                    'color_family' => 'Golden Ochre & Slate Grey',
                    'finishes' => ['Natural Cleft', 'Honed', 'Brushed'],
                    'description' => 'Distinctive natural slate characterized by intense golden ochre and amber hues accented with weathered rust markings across a sturdy natural cleft base.',
                    'features' => ['Luminous golden-ochre accents', 'Weathered rust character', 'Warm architectural wall cladding'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'California Gold',
                    'slug' => 'california-gold',
                    'color_family' => 'Rich Gold, Bronze & Pewter',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'A world-renowned exotic slate displaying an opulent fusion of rich metallic golds, bronzes, deep charcoal greys, and terracotta undertones.',
                    'features' => ['Exotic multi-tonal gold & bronze', 'Natural cleft depth', 'High visual movement'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'SP Autumn',
                    'slug' => 'sp-autumn',
                    'color_family' => 'Vibrant Amber & Terracotta',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'A select grade of Indian Autumn slate exhibiting more pronounced, vivid amber, copper, and terracotta waves over a calm cream-buff foundation.',
                    'features' => ['Enhanced chromatic intensity', 'Flowing mineral waves', 'Dramatic feature wall presence'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Multi Colour',
                    'slug' => 'multi-colour',
                    'color_family' => 'Plum, Rust, Sage & Grey',
                    'finishes' => ['Natural Cleft', 'Tumbled'],
                    'description' => 'A dynamic, polychromatic natural slate weaving together plum, rusty orange, muted sage, and charcoal in an expressive organic mosaic.',
                    'features' => ['Polychromatic earthy palette', 'Authentic cleavage relief', 'Resilient exterior performance'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Grey Slate',
                    'slug' => 'grey-slate',
                    'color_family' => 'Muted Pewter & Silver Grey',
                    'finishes' => ['Natural Cleft', 'Honed', 'Polished'],
                    'description' => 'An understated, monochromatic medium silver-to-pewter grey slate with fine laminar cleavage and serene architectural neutrality.',
                    'features' => ['Neutral architectural grey tone', 'Uniform fine-grained foliation', 'Timeless contemporary minimalism'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Chocolate',
                    'slug' => 'chocolate',
                    'color_family' => 'Deep Cocoa & Warm Earth',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'A warm, sophisticated metamorphic slate presenting uniform deep cocoa-brown and mocha tones with subtle velvety surface texture.',
                    'features' => ['Rich cocoa & mocha palette', 'Quiet uniform background', 'Warm organic warmth indoors & out'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
                [
                    'name' => 'M Green',
                    'slug' => 'm-green',
                    'color_family' => 'Olive & Forest Green',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'An earthy natural slate displaying rich olive, moss, and forest-green mineral layers with subtle silvery micaceous reflections.',
                    'features' => ['Deep biophilic green tones', 'Silvery micaceous sheen', 'Natural courtyard & terrace aesthetic'],
                    'sort_order' => 10,
                    'is_featured' => true,
                ],
                [
                    'name' => 'N Green',
                    'slug' => 'n-green',
                    'color_family' => 'Sage & Pale Emerald',
                    'finishes' => ['Natural Cleft', 'Honed'],
                    'description' => 'A tranquil, fine-grained slate characterized by fresh sage and soft jade-green tones that impart calmness to vertical wall panels and spa terraces.',
                    'features' => ['Tranquil sage-green foundation', 'Delicate natural cleavage', 'Serene spa and water-feature harmony'],
                    'sort_order' => 11,
                    'is_featured' => true,
                ],
                [
                    'name' => 'S White',
                    'slug' => 's-white',
                    'color_family' => 'Luminous Silver & Pale White',
                    'finishes' => ['Natural Cleft', 'Honed', 'Brushed'],
                    'description' => 'A rare, luminous micaceous quartzite-slate featuring a shimmering silver-white ground that catches natural daylight with soft crystalline brilliance.',
                    'features' => ['Luminous silver-white brightness', 'Natural micaceous quartz glint', 'Crisp architectural lightness'],
                    'sort_order' => 12,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Buching',
                    'slug' => 'black-buching',
                    'color_family' => 'Textured Obsidian & Deep Charcoal',
                    'finishes' => ['Buching (Chiseled Split Face)', 'Natural Cleft'],
                    'description' => 'Heavily textured architectural split-face black slate crafted through traditional buching (hammer-dressed chiseling) for pronounced 3D shadow depth.',
                    'features' => ['Heavy 3D chiseled relief', 'Deep non-reflective shadow play', 'Monumental exterior facade texture'],
                    'sort_order' => 13,
                    'is_featured' => true,
                ],
                [
                    'name' => 'N Green Buching',
                    'slug' => 'n-green-buching',
                    'color_family' => 'Textured Sage & Forest Green',
                    'finishes' => ['Buching (Chiseled Split Face)', 'Natural Cleft'],
                    'description' => 'Hand-chiseled buching finish applied to North Green slate, combining tactile rocky projections with calm, refreshing natural green mineral tones.',
                    'features' => ['Hand-chiseled textured face', 'Earthy green stone relief', 'Dynamic dimensional wall cladding'],
                    'sort_order' => 14,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Lime Green Buching',
                    'slug' => 'lime-green-buching',
                    'color_family' => 'Bright Lime & Pale Olive',
                    'finishes' => ['Buching (Chiseled Split Face)', 'Natural Cleft'],
                    'description' => 'An energetic architectural cladding stone showcasing radiant pale lime and olive green strata enhanced by deep chiseled split-face buching.',
                    'features' => ['Distinctive lime-green mineral layers', 'Sculptural chiseled cleavage', 'High tactile feature wall character'],
                    'sort_order' => 15,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Lime Pink Buching',
                    'slug' => 'lime-pink-buching',
                    'color_family' => 'Blush Pink & Pale Lime-Gold',
                    'finishes' => ['Buching (Chiseled Split Face)', 'Natural Cleft'],
                    'description' => 'A rare and artistic stone displaying an alluring interplay of soft blush-pink and pale lime-ochre hues across a heavily chiseled buching split surface.',
                    'features' => ['Artistic blush-pink and lime duality', 'Sculptural hammer-dressed texture', 'Stunning ambient raking light interplay'],
                    'sort_order' => 16,
                    'is_featured' => true,
                ],
            ],
            'limestones' => [
                [
                    'name' => 'Kadapa Black Polish',
                    'slug' => 'kadapa-black-polish',
                    'color_family' => 'Dense Jet Black',
                    'finishes' => ['Mirror Polished', 'Polished'],
                    'description' => 'Classic compact dolomitic limestone from Kadapa, polished to a deep, high-luster jet black with subtle charcoal undertones and near-zero porosity.',
                    'features' => ['High-reflectance obsidian depth', 'Ultra-dense dolomitic matrix', 'Exceptional stain resistance'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kadapa Black Honed Finish',
                    'slug' => 'kadapa-black-honed-finish',
                    'color_family' => 'Matte Charcoal & Graphite',
                    'finishes' => ['Honed', 'Fine Smooth'],
                    'description' => 'Smooth, low-sheen architectural surface exhibiting soft velvet matte charcoal tones that eliminate harsh specular reflections in contemporary interiors.',
                    'features' => ['Smooth matte velvet touch', 'Low-glare architectural tone', 'Minimalist monolithic flooring'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kadapa Black Rough',
                    'slug' => 'kadapa-black-rough',
                    'color_family' => 'Earthy Natural Black',
                    'finishes' => ['Natural Cleft', 'Rough Riven'],
                    'description' => 'Naturally split, uncalibrated cleft texture capturing rugged tectonic ridges and authentic geological relief, ideal for non-slip outdoor courtyards.',
                    'features' => ['Natural split-face riven texture', 'High slip resistance', 'Rugged exterior durability'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kadapa Black Flaming',
                    'slug' => 'kadapa-black-flaming',
                    'color_family' => 'Textured Basalt Black',
                    'finishes' => ['Thermal Flamed', 'Flamed'],
                    'description' => 'High-temperature thermal treatment that gently micro-spalls the limestone surface, yielding a textured crystalline grip and deep ash-black patina.',
                    'features' => ['Thermal-treated micro-texture', 'Superior wet-traction grip', 'Weatherproof facade & pool deck resilience'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Blue Rough',
                    'slug' => 'tandur-blue-rough',
                    'color_family' => 'Natural Steel Blue-Grey',
                    'finishes' => ['Natural Cleft', 'Rough'],
                    'description' => 'Celebrated Telangana limestone with an authentic natural split cleft face, displaying cool greenish-blue hues that naturally temper exterior heat.',
                    'features' => ['Natural cleft cleavage planes', 'Cool thermal footfeel', 'Centuries-proven civic heritage'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Blue Polish',
                    'slug' => 'tandur-blue-polish',
                    'color_family' => 'Deep Oceanic Blue-Grey',
                    'finishes' => ['Polished', 'Semi-Polished'],
                    'description' => 'Finely polished to illuminate deep teal, slate-blue, and greenish-grey mineral strata, bringing serene architectural elegance to spacious living halls.',
                    'features' => ['Rich oceanic blue-grey sheen', 'Subtle natural sedimentary grain', 'Easy maintenance interior flooring'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Blue Leather',
                    'slug' => 'tandur-blue-leather',
                    'color_family' => 'Tactile Slate Blue',
                    'finishes' => ['Leathered', 'Brushed'],
                    'description' => 'Diamond-brushed undulating leather finish that accentuates natural fossil contours while imparting a silky, tactile surface softness.',
                    'features' => ['Silky undulating relief', 'Soft satin tactile texture', 'Anti-fingerprint barefoot comfort'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Blue Satin Finish',
                    'slug' => 'tandur-blue-satin-finish',
                    'color_family' => 'Muted Teal & Silver Blue',
                    'finishes' => ['Satin', 'Lappato / Velvet'],
                    'description' => 'An exquisite eggshell satin treatment that strikes the perfect equilibrium between silky tactile smoothness and non-glare visual softness.',
                    'features' => ['Eggshell satin reflection', 'Subtle tonal depth', 'Contemporary architectural presence'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Yellow Rough',
                    'slug' => 'tandur-yellow-rough',
                    'color_family' => 'Warm Honey-Gold & Ochre',
                    'finishes' => ['Natural Cleft', 'Rough'],
                    'description' => 'Warm golden-ochre sedimentary limestone with a cleft natural face, radiating earthy warmth across sunlit courtyards, verandahs, and garden pathways.',
                    'features' => ['Warm sun-drenched golden hue', 'Natural slip-resistant cleft', 'Authentic vernacular warmth'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Tandur Yellow Leather',
                    'slug' => 'tandur-yellow-leather',
                    'color_family' => 'Velvety Honey & Amber',
                    'finishes' => ['Leathered', 'Brushed Antique'],
                    'description' => 'Warm honey-yellow stone softened by abrasive diamond brushes to create an antique, tactile leathered patina reminiscent of heritage European chateaux.',
                    'features' => ['Antique velvety touch', 'Enriched amber-gold color depth', 'Pleasant barefoot feel for villas'],
                    'sort_order' => 10,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kurnool Grey Polish',
                    'slug' => 'kurnool-grey-polish',
                    'color_family' => 'Ash & Silver Grey',
                    'finishes' => ['Polished', 'Mirror Finish'],
                    'description' => 'Luminous silver-grey limestone quarried in Kurnool, polished to highlight delicate micro-crystalline shifts and understated architectural neutrality.',
                    'features' => ['Pristine silver-grey clarity', 'Reflective micro-crystalline matrix', 'Harmonious neutral palette'],
                    'sort_order' => 11,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Kurnool Grey Satin Finish',
                    'slug' => 'kurnool-grey-satin-finish',
                    'color_family' => 'Pewter & Smoke Grey',
                    'finishes' => ['Satin', 'Honed-Brushed'],
                    'description' => 'Sophisticated smoke-grey limestone with a subtle satin patina that diffuses ambient daylight, creating quiet visual harmony in modern sanctuaries.',
                    'features' => ['Diffused daylight reflection', 'Gentle tactile micro-texture', 'Understated minimalist aesthetic'],
                    'sort_order' => 12,
                    'is_featured' => true,
                ],
            ],
            'sandstone' => [
                [
                    'name' => 'Dholpur Beige Sandstone',
                    'slug' => 'dholpur-beige-sandstone',
                    'color_family' => 'Warm Beige / Buff',
                    'finishes' => ['Natural Cleft', 'Honed', 'Shot Blasted'],
                    'description' => 'The celebrated benchmark of Indian architectural sandstone, quarried in Rajasthan. Distinguished by its uniform warm buff-beige tonality, subtle sedimentary layers, and remarkable thermal insulation.',
                    'features' => ['Uniform warm beige hue', 'Naturally slip resistant', 'High thermal resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Rainbow Sandstone',
                    'slug' => 'rainbow-sandstone',
                    'color_family' => 'Multi-tone Earth & Ochre',
                    'finishes' => ['Honed', 'Sawn', 'Brushed'],
                    'description' => 'A visually captivating fine-grained quartz sandstone with dramatic concentric waves and fluid color striations ranging from violet-brown and ochre to golden sand.',
                    'features' => ['Fluid sedimentary wave patterns', 'Rich warm earth striations', 'Distinct statement surface'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Teakwood Sandstone',
                    'slug' => 'teakwood-sandstone',
                    'color_family' => 'Golden Tan / Wood Grain',
                    'finishes' => ['Honed', 'Sawn', 'Sandblasted'],
                    'description' => 'Remarkably reminiscent of natural timber grain, this dense sedimentary stone displays warm golden-tan backgrounds traversed by linear brownish-yellow timber-like swirl patterns.',
                    'features' => ['Distinct wood-grain veining', 'Warm acoustic & tactile feel', 'Ideal for exterior feature walls'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Mandana Stone',
                    'slug' => 'mandana-stone',
                    'color_family' => 'Chocolate Red / Plum',
                    'finishes' => ['Natural Cleft', 'Honed', 'Calibrated'],
                    'description' => 'A dense, acid-resistant quartzitic sandstone with rich chocolate-red and plum undertones, known for centuries as one of the hardest and most resilient natural paving stones.',
                    'features' => ['Acid & frost resistant', 'Deep rich terracotta-plum tone', 'Heavy-duty architectural paving'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
            'cobble-stones' => [
                [
                    'name' => 'White Granite Cobble Handcut',
                    'slug' => 'white-granite-cobble-handcut',
                    'color_family' => 'Luminous Off-White & Quartz',
                    'finishes' => ['Hand-Cut', 'Natural Split Cleft'],
                    'description' => 'Hand-hewn white granite cobblestones featuring authentic natural split cleft surfaces and hand-dressed edges, delivering robust structural load-bearing and timeless masonry character.',
                    'features' => ['Hand-split artisanal character', 'Natural slip-resistant cleft', 'Heavy-duty carriageway resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Granite Cobble Handcut',
                    'slug' => 'black-granite-cobble-handcut',
                    'color_family' => 'Deep Charcoal & Obsidian',
                    'finishes' => ['Hand-Cut', 'Natural Split Cleft'],
                    'description' => 'Dense South Indian black granite cobbles hand-split along natural cleavage planes, offering rich charcoal depth and rugged tactile grip for heritage estate approaches.',
                    'features' => ['Natural hand-split fracture planes', 'Ultra-dense volcanic granite', 'Stain-resistant deep charcoal tone'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Yellow Granite Cobble Handcut',
                    'slug' => 'yellow-granite-cobble-handcut',
                    'color_family' => 'Warm Amber & Golden Ochre',
                    'finishes' => ['Hand-Cut', 'Natural Cleft'],
                    'description' => 'Artisanal hand-cut granite cobbles with warm honey and amber mineral specks, imbuing driveways and garden courtyards with Mediterranean warmth and enduring stone permanence.',
                    'features' => ['Sun-warmed golden hues', 'Authentic hand-hewn perimeter', 'Dependable all-weather traction'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Pink Granite Cobble Handcut',
                    'slug' => 'pink-granite-cobble-handcut',
                    'color_family' => 'Blush Rose & Feldspar Salmon',
                    'finishes' => ['Hand-Cut', 'Natural Split'],
                    'description' => 'Hand-split crystalline pink granite blocks highlighting natural potassium feldspar matrices, creating refined, distinguished courtyards and pedestrian walkways.',
                    'features' => ['Crystalline blush mineral tones', 'Hand-dressed rustic margins', 'Extreme compressive strength'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'White Granite Cobble 1inch Machine cut',
                    'slug' => 'white-granite-cobble-1inch-machine-cut',
                    'color_family' => 'Contemporary Clean White',
                    'finishes' => ['Machine Cut', 'Calibrated 1-Inch Sawn'],
                    'description' => 'Precisely dimensioned 1-inch calibrated white granite cobbles with sawn edges for tight, clean mortar joints and modern rectilinear groundplane geometry.',
                    'features' => ['Uniform 1-inch calibrated depth', 'Straight sawn joint profiles', 'Crisp modern architectural alignment'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Granite Cobbles 1inch Machine cut',
                    'slug' => 'black-granite-cobbles-1inch-machine-cut',
                    'color_family' => 'Matte Graphite & Jet Black',
                    'finishes' => ['Machine Cut', 'Calibrated Sawn'],
                    'description' => 'Precision diamond-sawn 1-inch black granite cobbles offering consistent module depth and crisp linear boundaries for sophisticated modern paving layouts.',
                    'features' => ['Precision sawn dimensional control', 'Consistent 1-inch paving module', 'High-contrast minimalist aesthetic'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Granite 1inch Machine cut Flaming',
                    'slug' => 'black-granite-1inch-machine-cut-flaming',
                    'color_family' => 'Textured Obsidian & Basalt Ash',
                    'finishes' => ['Thermal Flamed', '1-Inch Sawn Sides'],
                    'description' => 'Thermal-flamed top surface on 1-inch machine-cut black granite, bursting surface crystals to generate exceptional wet-weather traction and an elegant micro-rough patina.',
                    'features' => ['High-traction thermal spalled face', 'Machine-cut uniform dimensions', 'Maximum vehicular and pool wet grip'],
                    'sort_order' => 7,
                    'is_featured' => true,
                ],
                [
                    'name' => 'White 1inch Machine cut Flaming',
                    'slug' => 'white-1inch-machine-cut-flaming',
                    'color_family' => 'Textured Frost & Ash White',
                    'finishes' => ['Thermal Flamed', '1-Inch Machine Cut'],
                    'description' => 'High-temperature flamed white granite cobblestones featuring a slip-resistant textured face with sawn perimeter edges, balancing contemporary precision with organic texture.',
                    'features' => ['Non-slip thermal textured surface', 'Light-reflective frost white tone', 'Even 1-inch profile for pedestrian plazas'],
                    'sort_order' => 8,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Granite Full Box Cut Flaming',
                    'slug' => 'black-granite-full-box-cut-flaming',
                    'color_family' => 'Deep Ash Charcoal',
                    'finishes' => ['Full Box Sawn', 'Thermal Flamed Top'],
                    'description' => 'Six-side dimensional precision box-cut black granite blocks with a flamed top, engineered for high-precision commercial avenues and luxury vehicular carriageways.',
                    'features' => ['Full 6-sided precision sawn box cut', 'Thermal flamed non-slip walking surface', 'Ultra-tight joint installation capability'],
                    'sort_order' => 9,
                    'is_featured' => true,
                ],
                [
                    'name' => 'White Granite Full Box Cut Flaming',
                    'slug' => 'white-granite-full-box-cut-flaming',
                    'color_family' => 'Refined Granite White',
                    'finishes' => ['Full Box Sawn', 'Thermal Flamed Top'],
                    'description' => 'Engineered six-sided box-cut white granite cobbles with a tactile flamed top surface, delivering architectural alignment and luminous exterior elegance.',
                    'features' => ['Full box sawn volumetric precision', 'Tactile flamed surface grip', 'Architectural civic durability'],
                    'sort_order' => 10,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Granite 1inch Machine cut Bush Hammered',
                    'slug' => 'black-granite-1inch-machine-cut-bush-hammered',
                    'color_family' => 'Stippled Charcoal & Pewter',
                    'finishes' => ['Bush Hammered', '1-Inch Machine Cut'],
                    'description' => 'Mechanically point-chiselled bush hammered black granite cobbles displaying a uniform stippled texture that lightens the stone into subtle pewter tones while maximizing grip.',
                    'features' => ['Evenly stippled mechanical relief', 'Distinctive bush-hammered antique aesthetic', 'Zero-slip safety on ramps and terraces'],
                    'sort_order' => 11,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Lime Black cobbles Handcut',
                    'slug' => 'lime-black-cobbles-handcut',
                    'color_family' => 'Velvety Natural Black Limestone',
                    'finishes' => ['Hand-Cut', 'Natural Cleft Limestone'],
                    'description' => 'Artisan hand-dressed dolomitic black limestone cobbles with natural cleft faces, providing authentic tectonic texture and deep charcoal-black resonance.',
                    'features' => ['Authentic limestone cleft texture', 'Hand-dressed perimeter bevels', 'Historic European village cobblestone charm'],
                    'sort_order' => 12,
                    'is_featured' => true,
                ],
            ],
            'pebbles' => [
                [
                    'name' => 'White Marble Pebbles',
                    'slug' => 'white-marble-pebbles',
                    'color_family' => 'Crystalline Pure White',
                    'finishes' => ['Tumbled', 'Natural Matte'],
                    'description' => 'Pure crystalline Makrana white marble stones gently tumbled into smooth organic forms, reflecting ambient light with luminous purity across zen courtyards, planters, and dry garden scapes.',
                    'features' => ['Crystalline white mineral clarity', 'Smooth tumbled ergonomic contours', 'Bright reflective garden contrast'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Black Plain Unpolished Stone Pebbles',
                    'slug' => 'black-plain-unpolished-stone-pebbles',
                    'color_family' => 'Natural Matte Charcoal & Basalt',
                    'finishes' => ['Unpolished', 'Natural Tumbled'],
                    'description' => 'Naturally tumbled unpolished black basalt stones offering soft velvety charcoal tones that deepen to dramatic jet obsidian when touched by morning dew or water sprays.',
                    'features' => ['Soft matte non-glare surface', 'Deepens to obsidian when wet', 'Minimalist architectural grounding'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Brown Lining Rainbow Unpolished Stone Pebbles',
                    'slug' => 'brown-lining-rainbow-unpolished-stone-pebbles',
                    'color_family' => 'Variegated Earth & Rainbow Striations',
                    'finishes' => ['Unpolished', 'Natural Sedimentary'],
                    'description' => 'Fascinating unpolished sedimentary pebbles displaying concentric warm brown linings, ochre rings, and earthy rainbow bands sculpted by ancient geological deposition.',
                    'features' => ['Natural concentric mineral rings', 'Rich variegated earth palette', 'Distinct tactile accent character'],
                    'sort_order' => 3,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Desert Brown Stone Pebbles',
                    'slug' => 'desert-brown-stone-pebbles',
                    'color_family' => 'Warm Desert Tan & Amber',
                    'finishes' => ['Unpolished', 'Water-Worn'],
                    'description' => 'Earthy golden-brown river pebbles evoking sun-drenched desert terrains, providing natural warmth and seamless transitions around succulent beds and stone walkways.',
                    'features' => ['Sun-warmed desert buff tonality', 'Water-softened organic edges', 'Natural thermal insulation for soils'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Red Unpolished Stone Pebbles',
                    'slug' => 'red-unpolished-stone-pebbles',
                    'color_family' => 'Terracotta & Jasper Red',
                    'finishes' => ['Unpolished', 'Natural Cleft Tumbled'],
                    'description' => 'Rich iron-oxide red and terracotta unpolished pebbles introducing bold chromatic warmth and rustic earth permanence to courtyard water features and landscape borders.',
                    'features' => ['Deep iron-rich terracotta hues', 'Organic non-reflective matte face', 'High weather & freeze resilience'],
                    'sort_order' => 5,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Forest Green Unpolished Stone Pebbles',
                    'slug' => 'forest-green-unpolished-stone-pebbles',
                    'color_family' => 'Deep Moss & Serpentine Green',
                    'finishes' => ['Unpolished', 'Natural Tumbled'],
                    'description' => 'Serpentine-rich unpolished pebbles in organic forest and olive green tones, harmonizing seamlessly with foliage, moss gardens, and tranquil water reflection basins.',
                    'features' => ['Earthy moss and jade undertones', 'Tactile unpolished natural texture', 'Harmonious botanical integration'],
                    'sort_order' => 6,
                    'is_featured' => true,
                ],
            ],
            'quartz' => [
                [
                    'name' => 'Calacatta Nuvo Quartz',
                    'slug' => 'calacatta-nuvo-quartz',
                    'color_family' => 'Warm White',
                    'finishes' => ['Polished Slab', 'Suede'],
                    'description' => 'Large engineered quartz slabs featuring an opulent creamy white ground traversed by broad, cascading grey veins for monolithic islands.',
                    'features' => ['Large engineered slab format', 'Broad continuous veining', 'Non-porous architectural resilience'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Statuario Classic Quartz',
                    'slug' => 'statuario-classic-quartz',
                    'color_family' => 'Crisp White',
                    'finishes' => ['Polished Slab', 'Matte'],
                    'description' => 'A masterwork engineered quartz surface offering crisp cool-white slab clarity and flowing graphite veining with total pattern consistency.',
                    'features' => ['Crisp white slab continuity', 'Flowing graphite veining', 'Seamless waterfall edge capability'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Eternal Charcoal Quartz',
                    'slug' => 'eternal-charcoal-quartz',
                    'color_family' => 'Deep Charcoal',
                    'finishes' => ['Suede Slab', 'Polished'],
                    'description' => 'An intense deep charcoal engineered quartz slab traversed by fine, luminous white lightning veins for striking contemporary worktops.',
                    'features' => ['Deep charcoal slab depth', 'Fine luminous contrast veins', 'High scratch and stain resistance'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Pure Blanco Quartz',
                    'slug' => 'pure-blanco-quartz',
                    'color_family' => 'Monochrome White',
                    'finishes' => ['Polished Slab'],
                    'description' => 'A pure, minimalist monochromatic white quartz slab offering uninterrupted architectural surface continuity across expansive surfaces.',
                    'features' => ['Pure monochromatic surface', 'Unbroken visual continuity', 'Architectural minimalist clarity'],
                    'sort_order' => 4,
                    'is_featured' => false,
                ],
            ],
            'sculptures' => [
                [
                    'name' => 'Monolithic Carved Basin',
                    'slug' => 'monolithic-carved-basin',
                    'color_family' => 'Natural Stone',
                    'finishes' => ['Hand-Chiseled', 'Honed Interior'],
                    'description' => 'Carved from a singular block of natural stone with a rugged artisan exterior and a silky honed interior basin that celebrates raw materiality.',
                    'features' => ['Singular solid stone block', 'Dual textured surface finish', 'Bespoke sculptural focal point'],
                    'sort_order' => 1,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Architectural Stone Totem',
                    'slug' => 'architectural-stone-totem',
                    'color_family' => 'Weathered Stone',
                    'finishes' => ['Fine Bush-Hammered'],
                    'description' => 'A monumental hand-carved stone column with geometric reliefs that functions as a grounding architectural element for courtyards and entryways.',
                    'features' => ['Monumental vertical presence', 'Artisan geometric relief', 'Timeless outdoor permanence'],
                    'sort_order' => 2,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Fluted Classical Pedestal',
                    'slug' => 'fluted-classical-pedestal',
                    'color_family' => 'White Marble',
                    'finishes' => ['Honed', 'Antique Patina'],
                    'description' => 'A solid white marble pedestal hand-carved with architectural fluting, designed to anchor private art galleries and stately entry foyers.',
                    'features' => ['Hand-carved vertical fluting', 'Noble white marble grain', 'Architectural gallery presentation'],
                    'sort_order' => 3,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Contemplative Stone Vessel',
                    'slug' => 'contemplative-stone-vessel',
                    'color_family' => 'Dark Basalt',
                    'finishes' => ['Textured Exterior', 'Smooth Bowl'],
                    'description' => 'A wide, shallow contemplative water vessel carved from natural basalt, inviting reflection and stillness into private courtyards.',
                    'features' => ['Organic low-profile form', 'Natural water interaction', 'Quiet meditative presence'],
                    'sort_order' => 4,
                    'is_featured' => true,
                ],
            ],
        ];

        foreach ($varietiesByCollection as $collectionSlug => $varieties) {
            $collection = Collection::where('slug', $collectionSlug)->first();

            if (! $collection) {
                continue;
            }

            // Remove obsolete varieties not in the configured list
            $validSlugs = array_column($varieties, 'slug');
            Variety::where('collection_id', $collection->id)
                ->whereNotIn('slug', $validSlugs)
                ->delete();

            foreach ($varieties as $varietyData) {
                Variety::updateOrCreate(
                    [
                        'collection_id' => $collection->id,
                        'slug' => $varietyData['slug'],
                    ],
                    [
                        'name' => $varietyData['name'],
                        'color_family' => $varietyData['color_family'],
                        'finishes' => $varietyData['finishes'],
                        'description' => $varietyData['description'],
                        'features' => $varietyData['features'],
                        'specifications' => [],
                        'is_featured' => $varietyData['is_featured'],
                        'is_active' => true,
                        'sort_order' => $varietyData['sort_order'],
                    ]
                );
            }
        }
    }
}
